package tubes_pbo;

public class Penjahit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Penjahit.class.getName());

    public Penjahit() {
        initComponents();
        tampilkanData();
    }
    
    private void tampilkanData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (ModelPelanggan p : DataStore.listPelanggan) {
            Object[] row = {
                p.getNama(),
                p.getNoHp(),
                p.getAlamat(),
                "-",
               "Rp " + p.getTotalHarga(),
                p.getStatusPesanan(),   
                p.getStatusPembayaran() 
            };
            model.addRow(row);
        }

        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        ((javax.swing.table.DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jasa jahit waifjsoianfa (Penjahit)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "No Telepon", "Alamat", "Detail Pesanan", "Status Pesanan", "Total Harga", "Status Pembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 51, 51));
        jTable1.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(203, 203, 203)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// Edit
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int barisTerpilih = jTable1.getSelectedRow();
        
        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Silakan pilih/klik salah satu baris data pelanggan di tabel terlebih dahulu!", 
                    "Peringatan", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModelPelanggan pelangganTerpilih = DataStore.listPelanggan.get(barisTerpilih);

        String hargaInput = javax.swing.JOptionPane.showInputDialog(this, 
                "Masukkan Total Harga untuk " + pelangganTerpilih.getNama() + ":", 
                String.valueOf(pelangganTerpilih.getTotalHarga()));
        
        if (hargaInput == null) return;

        int hargaBaru = pelangganTerpilih.getTotalHarga();
        try {
            hargaBaru = Integer.parseInt(hargaInput.trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input harga harus berupa angka!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] pilihanStatus = {"Pending", "Sedang Dijahit", "Selesai"};
        String statusBaru = (String) javax.swing.JOptionPane.showInputDialog(this, 
                "Ubah Status Pesanan untuk " + pelangganTerpilih.getNama() + ":", 
                "Update Status Pesanan", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, 
                null, pilihanStatus, pelangganTerpilih.getStatusPesanan());

        if (statusBaru == null) return; 

        String[] pilihanBayar = {"Belum Bayar", "Lunas"};
        String bayarBaru = (String) javax.swing.JOptionPane.showInputDialog(this, 
                "Ubah Status Pembayaran untuk " + pelangganTerpilih.getNama() + ":", 
                "Update Status Pembayaran", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, 
                null, pilihanBayar, pelangganTerpilih.getStatusPembayaran());

        if (bayarBaru == null) return;

        pelangganTerpilih.setTotalHarga(hargaBaru); 
        pelangganTerpilih.setStatusPesanan(statusBaru);
        pelangganTerpilih.setStatusPembayaran(bayarBaru);

        tampilkanData();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Data Pesanan & Harga berhasil diperbarui!");
    }//GEN-LAST:event_jButton1ActionPerformed
// Delete

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int barisTerpilih = jTable1.getSelectedRow();
        
        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Silakan pilih/klik baris data pelanggan yang ingin dihapus!", 
                    "Peringatan", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModelPelanggan pelangganTerpilih = DataStore.listPelanggan.get(barisTerpilih);

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin menghapus data pelanggan '" + pelangganTerpilih.getNama() + "'?",
                "Konfirmasi Hapus",
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            DataStore.listPelanggan.remove(barisTerpilih);
            
            tampilkanData();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data pelanggan berhasil dihapus!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Penjahit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}