package tubes_pbo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class Penjahit extends javax.swing.JFrame implements InterfacePenjahit {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Penjahit.class.getName());
    
    // Variabel penunjuk pembantu untuk memetakan indeks baris tabel ke objek aslinya
    private java.util.ArrayList<ModelPelanggan> penunjukPelanggan = new java.util.ArrayList<>();
    private java.util.ArrayList<ModelPesanan> penunjukPesanan = new java.util.ArrayList<>();

    public Penjahit() {
        initComponents();
        tampilkanData();
    }
    
    @Override
    public void tampilkanData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        penunjukPelanggan.clear();
        penunjukPesanan.clear();

        try (Connection conn = Koneksi.getConnection()) {
            String sql = "SELECT p.id AS pesanan_id, p.user_id, p.nama_pesanan, p.detail_pesanan, "
                       + "p.status_pesanan, p.total_harga, p.status_pembayaran, "
                       + "u.nama, u.no_hp, u.alamat "
                       + "FROM pesanan p "
                       + "JOIN `user` u ON p.user_id = u.id "
                       + "WHERE u.role = 'Pelanggan' "
                       + "ORDER BY p.id DESC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                ModelPelanggan pelanggan = new ModelPelanggan(
                        rs.getInt("user_id"),
                        rs.getString("nama"),
                        rs.getString("no_hp"),
                        rs.getString("alamat"),
                        ""
                );

                ModelPesanan pesanan = new ModelPesanan(
                        rs.getInt("pesanan_id"),
                        rs.getInt("user_id"),
                        rs.getString("nama_pesanan"),
                        rs.getString("detail_pesanan"),
                        rs.getString("status_pesanan"),
                        rs.getInt("total_harga"),
                        rs.getString("status_pembayaran")
                );

                Object[] row = {
                    pelanggan.getNama(),
                    pelanggan.getNoHp(),
                    pelanggan.getAlamat(),
                    pesanan.getNamaPesanan(),
                    pesanan.getDetailPesanan(),
                    pesanan.getStatusPesanan(),
                    "Rp " + pesanan.getTotalHarga(),
                    pesanan.getStatusPembayaran()
                };
                model.addRow(row);

                penunjukPelanggan.add(pelanggan);
                penunjukPesanan.add(pesanan);
            }

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
                    .setHorizontalAlignment(JLabel.CENTER);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal menampilkan data pesanan: " + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jasa jahit waifjsoianfa (Penjahit)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "No Telepon", "Alamat", "Pesanan", "Detail Pesanan", "Status Pesanan", "Total Harga", "Pembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 51, 51));
        jTable1.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void editPesanan() {
        int barisTerpilih = jTable1.getSelectedRow();

        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this,
                    "Silakan pilih/klik salah satu baris data pesanan di tabel terlebih dahulu!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModelPelanggan pelangganTerpilih = penunjukPelanggan.get(barisTerpilih);
        ModelPesanan pesananTerpilih = penunjukPesanan.get(barisTerpilih);

        String detailBaru = JOptionPane.showInputDialog(this,
                "Edit Detail Keterangan Pesanan milik " + pelangganTerpilih.getNama() + ":", pesananTerpilih.getDetailPesanan());
        if (detailBaru == null) return;

        String hargaInput = JOptionPane.showInputDialog(this,
                "Masukkan Total Harga Baru (Angka):", String.valueOf(pesananTerpilih.getTotalHarga()));
        if (hargaInput == null) return;

        int hargaBaru;
        try {
            hargaBaru = Integer.parseInt(hargaInput.replace(".", "").replace(",", "").trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka murni!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] pilihanStatus = {"Pending", "Ditolak", "Sedang Dijahit", "Selesai"};
        String statusBaru = (String) JOptionPane.showInputDialog(this,
                "Ubah Status Pesanan:", "Update Status",
                JOptionPane.QUESTION_MESSAGE, null, pilihanStatus, pesananTerpilih.getStatusPesanan());
        if (statusBaru == null) return;

        String[] pilihanBayar = {"Belum Bayar", "Menunggu Konfirmasi (Transfer)", "Lunas (Transfer)", "Lunas (Tunai)"};
        String bayarBaru = (String) JOptionPane.showInputDialog(this,
                "Ubah Status Pembayaran:", "Update Pembayaran",
                JOptionPane.QUESTION_MESSAGE, null, pilihanBayar, pesananTerpilih.getStatusPembayaran());
        if (bayarBaru == null) return;

        try (Connection conn = Koneksi.getConnection()) {
            String sql = "UPDATE pesanan SET detail_pesanan = ?, total_harga = ?, status_pesanan = ?, status_pembayaran = ? WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, detailBaru.trim());
            pst.setInt(2, hargaBaru);
            pst.setString(3, statusBaru);
            pst.setString(4, bayarBaru);
            pst.setInt(5, pesananTerpilih.getId());
            pst.executeUpdate();

            tampilkanData();
            JOptionPane.showMessageDialog(this, "Data pesanan berhasil diperbarui dan tersimpan ke database!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mengupdate data pesanan: " + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void hapusPesanan() {
        int barisTerpilih = jTable1.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris data pesanan yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ModelPelanggan pelangganTerpilih = penunjukPelanggan.get(barisTerpilih);
        ModelPesanan pesananTerpilih = penunjukPesanan.get(barisTerpilih);

        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin menghapus data pesanan '" + pesananTerpilih.getNamaPesanan() + "' milik " + pelangganTerpilih.getNama() + "?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try (Connection conn = Koneksi.getConnection()) {
                String sql = "DELETE FROM pesanan WHERE id = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, pesananTerpilih.getId());
                pst.executeUpdate();

                tampilkanData();
                JOptionPane.showMessageDialog(this, "Data pesanan berhasil dihapus dari database!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                        "Gagal menghapus data pesanan: " + e.getMessage(),
                        "Error Database",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

// Button Edit
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        editPesanan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hapusPesanan();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Penjahit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}